export const bookCategories = [
    { label: "Fiction", value: "fiction" },
    { label: "Non-Fiction", value: "non-fiction" },
    { label: "Childrens", value: "childrens" },
    { label: "Young Adult", value: "young-adult" },
    { label: "Adult", value: "adult" },
    { label: "Romance", value: "romance" },
    { label: "Mystery", value: "mystery" },
    { label: "Science Fiction", value: "science-fiction" },
    { label: "Fantasy", value: "fantasy" },
    { label: "Historical Fiction", value: "historical-fiction" },
    { label: "Historical", value: "historical" },
    { label: "Biography", value: "biography" },
    { label: "Self-Help", value: "self-help" },
    { label: "Travel", value: "travel" },
    { label: "Cooking", value: "cooking" },
    { label: "Art", value: "art" },
    { label: "Photography", value: "photography" },
    { label: "Business", value: "business" },
    { label: "Technology", value: "technology" },
    { label: "Science", value: "science" },
    { label: "Math", value: "math" },
    { label: "Physics", value: "physics" },
    { label: "Chemistry", value: "chemistry" },
    { label: "Biology", value: "biology" },
    { label: "Computer Science", value: "computer-science" },
    { label: "Programming", value: "programming" },
    { label: "Machine Learning", value: "machine-learning" },
    { label: "Deep Learning", value: "deep-learning" },
    { label: "Robotics", value: "robotics" },
    { label: "Cybersecurity", value: "cybersecurity" },
    { label: "Cryptography", value: "cryptography" },
    { label: "Web Development", value: "web-development" },
    { label: "App Development", value: "app-development" },
    { label: "Mobile Development", value: "mobile-development" },
    { label: "Game Development", value: "game-development" },
    { label: "Software Development", value: "software-development" },
    { label: "Networking", value: "networking" },
    { label: "Database", value: "database" },
    { label: "Data Management", value: "data-management" },
    { label: "Data Science", value: "data-science" },
    { label: "Horror", value: "Horror" },
    { label: "Psychological", value: "psychological" },
    { label: "Religious", value: "religious" },
    { label: "Philosophy", value: "philosophy" },
    { label: "Religion", value: "religion" },
    { label: "Thriller", value: "thriller" },
    { label: "Poetry", value: "poetry" },
    { label: "Drama", value: "drama" },
    { label: "Graphic Novel", value: "graphic-novel" },
    { label: "Manga", value: "manga" },
    { label: "Autobiography", value: "autobiography" },
    { label: "Memoir", value: "memoir" },
    { label: "Economics", value: "economics" },
    { label: "Politics", value: "politics" },
    { label: "Sociology", value: "sociology" },
    { label: "Psychology", value: "psychology" },
    { label: "Anthropology", value: "anthropology" },
    { label: "Education", value: "education" },
    { label: "Health", value: "health" },
    { label: "Fitness", value: "fitness" },
    { label: "Sports", value: "sports" },
    { label: "Music", value: "music" },
    { label: "Film", value: "film" },
    { label: "Theater", value: "theater" },
    { label: "Architecture", value: "architecture" },
    { label: "Design", value: "design" },
    { label: "Crafts", value: "crafts" },
    { label: "Gardening", value: "gardening" },
    { label: "Humor", value: "humor" },
    { label: "True Crime", value: "true-crime" },
    { label: "Parenting", value: "parenting" },
    { label: "Relationships", value: "relationships" },
    { label: "Law", value: "law" },
    { label: "Medicine", value: "medicine" },
    { label: "Environment", value: "environment" },
    { label: "Nature", value: "nature" },
    { label: "Astronomy", value: "astronomy" },
    { label: "Geology", value: "geology" },
    { label: "Archaeology", value: "archaeology" },
    { label: "Linguistics", value: "linguistics" },
    { label: "Foreign Language", value: "foreign-language" },
    { label: "Dystopia", value: "dystopia" },
    { label: "Classics", value: "classics" },
    { label: "Steampunk", value: "steampunk" },
    { label: "Paranormal", value: "paranormal" },
    { label: "Urban Fantasy", value: "urban-fantasy" },
    { label: "Magical Realism", value: "magical-realism" },
    { label: "Alternate History", value: "alternate-history" },
    { label: "Gothic", value: "gothic" },
    { label: "Cyberpunk", value: "cyberpunk" },
    { label: "Apocalyptic", value: "apocalyptic" },
    { label: "Post-Apocalyptic", value: "post-apocalyptic" },
    { label: "Time Travel", value: "time-travel" },
    { label: "Space Opera", value: "space-opera" },
    { label: "Superhero", value: "superhero" },
    { label: "Mythology", value: "mythology" },
    { label: "Fairy Tales", value: "fairy-tales" },
    { label: "Folklore", value: "folklore" },
    { label: "Satire", value: "satire" },
    { label: "Espionage", value: "espionage" },
    { label: "Westerns", value: "westerns" },
    { label: "Erotica", value: "erotica" },
    { label: "LGBTQ+", value: "lgbtq" },
    { label: "Feminism", value: "feminism" },
    { label: "Afrofuturism", value: "afrofuturism" },
    { label: "Speculative Fiction", value: "speculative-fiction" },
    { label: "Surrealism", value: "surrealism" },
    { label: "Experimental", value: "experimental" },
    { label: "Epistolary", value: "epistolary" },
    { label: "Metafiction", value: "metafiction" },
    { label: "Bildungsroman", value: "bildungsroman" },
    { label: "Travelogue", value: "travelogue" },
    { label: "Nautical", value: "nautical" },
];